# Generated by Django 3.2.5 on 2021-08-07 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email', max_length=80, unique=True)),
                ('password', models.CharField(max_length=80)),
                ('phone_number', models.CharField(help_text='Phone_number', max_length=20, unique=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(blank=True, editable=False, max_length=100)),
            ],
        ),
    ]
