# Generated by Django 3.2.5 on 2021-08-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210806_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTP',
            field=models.PositiveIntegerField(blank=True, default=1234),
            preserve_default=False,
        ),
    ]
