# Generated by Django 3.2.5 on 2021-08-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_otp_verified_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_active',
            field=models.BooleanField(default=False),
        ),
    ]
