# Generated by Django 3.2.5 on 2021-08-09 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_user',
            field=models.BooleanField(default=False),
        ),
    ]
